name = "flareact-site"
type = "webpack"
account_id = ""
workers_dev = false
route = "flareact.com/*"
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
